### PR TITLE
JPDL migration tool tests to community

### PR DESCRIPTION
**Pull request by jakubschwan**
Add test to community from RedHat test suite
All tests passed

### CODE REVIEW

**Comment by mrietveld** [comment]
Great work!

**Comment by mrietveld** [comment]
@eschabell Do you want to be responsible for managing PR's on this repo?

**Comment by psiroky** [comment]
@eschabell @mrietveld what do think about moving the jbpmmigration directly into jbpm repo? That way it would much easier from maintenance point of view as we could share all the versions and also test with the latest jBPM builds.

**Comment by eschabell** [comment]
Merging and commented on the removal of decisions. I have no problems with this going into jbpm main repo.

**Comment by mrietveld** [comment]
+1 

@psiroky When you move it into the main repo, please rename to "jbpm-migration", conform our naming schema. 

Thanks!

**Pull request merged**
